/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_clusteringservice_ClusteringService */

#ifndef _Included_com_example_clusteringservice_ClusteringService
#define _Included_com_example_clusteringservice_ClusteringService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_clusteringservice_ClusteringService
 * Method:    writeFPGAFND
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_clusteringservice_ClusteringService_writeFPGAFND
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
