20111599:
	arm-none-linux-gnueabi-gcc -static devices/gpio.c devices/fpga.c devices/device.c main.c debug.c modeproc.c -o 20111599  -lm
#gcc -static devices/gpio.c devices/fpga.c devices/device.c main.c debug.c modeproc.c -o 20111599 -g
clean:
	rm 20111599
